# Default values for deploying the Python Flask application
image:
  repository: docker.io/sudheerpailu1017/sample-python-app:latest

service:
  type: ClusterIP
  port: 8080

replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"
